Changed uppercase 'Model' to lowercase in index.js
The file that needs to be required is './lib/model' not './lib/Model'. Node returns 
Error: Cannot find module './lib/Model'